# Generated by Django 3.1.6 on 2021-02-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kunden_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('telefon', models.IntegerField(unique=True)),
                ('sorte', models.CharField(max_length=13)),
                ('size', models.CharField(max_length=8)),
            ],
        ),
    ]
